[package]
name = "wifi-qr-code-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12.0"
image = "0.23.0"
clap = {version = "4.0.15", features = ["derive"]}
